### ISSUE TITLE
Dashboards don't sync between desktop/phone

### ISSUE THREAD

**Issue by ixici** [matthiasn/lotti#1040]
Scenario:
- have sync working
- create some dashboards on desktop app
- create some dashboards on phone app
- observe they are not sync-ing
<img width="618" alt="Screenshot 2022-06-10 at 20 14 08" src="https://user-images.githubusercontent.com/55126809/173121059-e636e9b6-951b-42b1-94c8-7481ed4fd472.png">

![signal-2022-06-10-201439_001](https://user-images.githubusercontent.com/55126809/173121177-1c33193a-d40a-45ca-93d0-dff86665ba8e.png)

**Comment by matthiasn** [comment]
@ixici thanks for the report. I tried to recreate the issue but new dashboards are synced fine for me between devices. Is it possible that you had previously created and deleted dashboards with the same name? Dashboards (and other entities) were only marked as deleted but the `UNIQUE` constraint on the name field in the respective database table would then not allow creating a new dashboard with a name that already existed but was marked as deleted.

In #1043 I added a maintenance task for purging items marked as deleted, and in #1042 I changed the name field to now be filled with the unique ID of a dashboard, since that field is not used anyway. This was easier to achieve than a database migration removing the column altogether. Could you please try to run the maintenance task in the latest version and then trying to create a new dashboard and check if it syncs between devices? You can find that task under `Settings > Advanced Settings > Maintenance > Purge deleted items`. The task also creates a backup of the database file, just in case anything goes wrong.

**Comment by matthiasn** [comment]
No that was not it. Instead the problem should now be fixed in #1045. Please also run the mentioned maintenance task. Thanks!

**Comment by ixici** [comment]
Dashboards are synced now with the latest updates.
